---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  production.json: |
    {
      "imageAcl": {
        "allowed": {{ .Values.allowedImages | toJson }},
        "blocked": {{ .Values.blockedImages | toJson }},
        "strictMode": {{ .Values.strictMode }}
      },
      "log": {
        "level": "{{ .Values.logLevel }}"
      },
      "tls": {
        "enabled": true
      }
    }