apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-admission-controller-starter.fullname" . }}
  labels:
    {{- include "kube-admission-controller-starter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "kube-admission-controller-starter.selectorLabels" . | nindent 4 }}
